CREATE DATABASE entertainMedb;

USE entertainMedb;

CREATE TABLE movies(
id INT NOT NULL AUTO_INCREMENT,
rank_no INT NOT NULL,
title VARCHAR(255) NOT NULL,
genre VARCHAR(255) NOT NULL,
description VARCHAR(255) NOT NULL,
director VARCHAR(255) NOT NULL,
actors VARCHAR(255) NOT NULL,
year INT NOT NULL,
runtime INT NOT NULL,
rating DECIMAL(10,2) NOT NULL,
votes INT NOT NULL,
revenue DECIMAL(10,3),
metascore INT NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE shortlist(
id INT NOT NULL AUTO_INCREMENT,
movie_id INT NOT NULL,
PRIMARY KEY (id), 
FOREIGN KEY (movie_id) REFERENCES movies(id) 
);

CREATE TABLE review(
id INT NOT NULL AUTO_INCREMENT,
movie_id INT NOT NULL,
score INT NOT NULL,
comments VARCHAR(255) NOT NULL,
PRIMARY KEY (id), 
FOREIGN KEY (movie_id) REFERENCES movies(id) 
);
USE entertainMedb;
DROP TABLE movies;

CREATE TABLE movies(
id INT NOT NULL AUTO_INCREMENT,
title VARCHAR(255) NOT NULL,
year INT NOT NULL,
rated VARCHAR(255) NOT NULL,
released VARCHAR(255) NOT NULL,
runtime INT NOT NULL,
genre VARCHAR(255) NOT NULL,
director VARCHAR(255) NOT NULL,
writer VARCHAR(255) NOT NULL,
actors VARCHAR(255) NOT NULL,
plot VARCHAR(255) NOT NULL,
language VARCHAR(255) NOT NULL,
country VARCHAR(255) NOT NULL,
awards VARCHAR(255) NOT NULL,
poster VARCHAR(255) NOT NULL,
ratings VARCHAR(255) NOT NULL,
metascore INT NOT NULL,
imdbID DECIMAL(10,3),
type VARCHAR(255) NOT NULL,
dvd VARCHAR(255),
box_office INT,
production VARCHAR(255),
website VARCHAR(255),
response VARCHAR(255), 
PRIMARY KEY (id)
);
